{
    "CVSSv3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "breadcrumbItems": [
        {
            "label": "Snyk Vulnerability Database",
            "url": "/vuln"
        },
        {
            "label": "Unmanaged (C/C++)",
            "url": "/vuln/unmanaged"
        },
        {
            "findByTestHook": "filter",
            "label": "tianocore/edk2"
        }
    ],
    "credit": [
        "Unknown"
    ],
    "cvssDetails": [
        {
            "assigner": "Red Hat",
            "cvssV3BaseScore": 7.5,
            "cvssV3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "modificationTime": "2024-01-17T13:48:36.697323Z",
            "severity": "high"
        }
    ],
    "cvssScore": 7.5,
    "description": "## Overview Affected versions of this package are vulnerable to Loop with Unreachable Exit Condition ('Infinite Loop') due to improper handling of unknown options in the `Destination Options` header. An attacker can cause denial of service. ## Remediation There is no fixed version for `tianocore/edk2`. ## References - [Additional Information](https://blog.quarkslab.com/pixiefail-nine-vulnerabilities-in-tianocores-edk-ii-ipv6-network-stack.html) - [RedHat Bugzilla Bug](https://bugzilla.redhat.com/show_bug.cgi?id=2258691) ",
    "disclosureTime": "2024-01-16T00:00:00Z",
    "epssDetails": null,
    "exploitMaturity": "Not Defined",
    "id": "SNYK-UNMANAGED-TIANOCOREEDK2-6170055",
    "identifiers": {
        "CVE": [
            "CVE-2023-45232"
        ],
        "CWE": [
            "CWE-835"
        ]
    },
    "language": "cpp",
    "malicious": false,
    "packageManager": "unmanaged",
    "packageName": "tianocore/edk2",
    "publicationTime": "2024-01-17T21:28:11.546250Z",
    "remediation": "There is no fixed version for tianocore/edk2 . ",
    "semver": {
        "vulnerable": [
            "[0]"
        ]
    },
    "severity": "high",
    "socialTrendAlert": false,
    "title": "Loop with Unreachable Exit Condition ('Infinite Loop')",
    "vulnDescription": {
        "Overview": "Affected versions of this package are vulnerable to Loop with Unreachable Exit Condition ('Infinite Loop') due to improper handling of unknown options in the Destination Options header. An attacker can cause denial of service. ",
        "References": [
            "https://blog.quarkslab.com/pixiefail-nine-vulnerabilities-in-tianocores-edk-ii-ipv6-network-stack.html",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2258691"
        ]
    },
    "vulnerableVersions": "[0]"
}